### ISSUE TITLE
Big mek missing options when in mega armour

### ISSUE THREAD

**Issue by kolslaw68** [normanthesquid/wh40k-fundapocalypse#80]
**Orks**

**Big Mek**

Incorrect Datasheet

The big mek is missing the following wargear options when equipped:

Can be equipped with a tellyport blasta **(Power Rating +1)** or can also have a Kustom Forcefield **(Power Rating +1)**.  If this unit has a Kustom Force Field it has the following additional abilities: **Kustom Forcefield**

Tellyport Blasta Profile:
Type: Heavy,  Range: 12", Attacks: 1, SAP 9+, SAT 9+, Abilities: Destroyer

**Kustom Force Field**: Subtract 1 from wound rolls for attacks made by ranged weapons that target **<Clan>** units whilst they are wholly within 9" of any friendly **<Clan>** units with a Kustom Force Field

**Comment by normanthesquid** [comment]
will be fixed by https://github.com/BSData/wh40k-apocalypse/issues/158

**Comment by normanthesquid** [comment]
The options are there, you just need to drill down. See BSData#158
