### ISSUE TITLE
Warlord titan datasheet update

### ISSUE THREAD

**Issue by Dakkarmortis** [normanthesquid/wh40k-fundapocalypse#86]
**Faction:**
Imperium - Titan legions

**Unit:**
Warlord Battle Titan

**Issue Type:** 
Update datasheet

**Description:**
add "+1 attack when dual wielding" for using 2 Arioch Power Claws

**Comment by normanthesquid** [comment]
We are going to add the apoc version of Wrecker instead, as shown on the Ironclad dreadnought, which lets you reroll ones
